In [1]:
import numpy as np

In [6]:
#Create arrays using np.array(), np.zeros(), np.ones(), np.arange()

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((2, 3))
arr3 = np.ones((3, 3))
arr4 = np.arange(0, 10, 2)

arr1, arr2, arr3, arr4

(array([1, 2, 3, 4, 5]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]))

# Reshaping

In [5]:
reshaped = arr4.reshape(5, 1)
reshaped


array([[0],
       [2],
       [4],
       [6],
       [8]])

# Slicing

In [7]:
slice1 = arr1[1:4]
slice2 = arr3[:, 1]

slice1, slice2


(array([2, 3, 4]), array([1., 1., 1.]))

# Mathematical Operations

In [12]:
add = arr1 + 10
multiply = arr1 * 2
dot_product = np.dot([1, 2, 3], [4, 5, 6])

add, multiply, dot_product


(array([11, 12, 13, 14, 15]), array([ 2,  4,  6,  8, 10]), 32)

# Statistical Functions

In [13]:
mean = np.mean(arr1)
median = np.median(arr1)
std = np.std(arr1)
variance = np.var(arr1)

mean, median, std, variance


(3.0, 3.0, 1.4142135623730951, 2.0)

# Broadcasting

In [14]:
broadcasted = arr3 + 5
broadcasted


array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])